version: "3"
services:
  eureka-server:
    image: eureka-server
    container_name: eureka-server
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - eureka-network

  amazon-shopping:
    image: amazon-shopping
    container_name: amazon-shopping
    build: ./amazon-shopping
    ports:
      - "9999:9999"
    networks:
      - eureka-network
    depends_on:
      - eureka-server
      - payment-service
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka"

  payment-service:
    image: payment-service
    container_name: payment-service
    build: ./payment-service
    ports:
      - "8888:8888"
    networks:
     - eureka-network
    depends_on:
      - eureka-server
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka"
  
  config-server:
    image: config-server
    container_name: config-server
    build: ./config-server
    ports:
      - "8882:8882"
    networks:
     - eureka-network
   

  employee-provider:
    image: employee-provider
    container_name: employee-provider
    build: ./employee-provider
    ports:
      - "8883:8883"
    networks:
     - eureka-network
   

  getemployee-client:
    image: getemployee-client
    container_name: getemployee-client
    build: ./getemployee-client
    ports:
      - "8884:8884"
    networks:
     - eureka-network
    depends_on:
     - config-server
      
networks:
  eureka-network:
