version: "3.7"
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    extra_hosts: ['host.docker.internal:host-gateway']
    ports:
      - "9411:9411"
  discovery-service:
      image: piomin/eureka-server:0.0.1-SNAPSHOT
      container_name: eureka-server
      ports:
        - "8761:8761"
      healthcheck:
        test: curl fail http://localhost:8761/eureka/v2/apps || exit 1
        interval: 4s
        timeout: 2s
        retries: 3
  payment-service:
      image: piomin/payment-service:0.0.1-SNAPSHOT
      container_name: payment-service
      ports:
        - "9999:9999"
      links:
        - discovery-service
        - zipkin
  amazon-shopping:
      image: piomin/amazon-shopping:0.0.1-SNAPSHOT
      container_name: amazon-shopping
      ports:
        - "8888:8888"
      links:
        - discovery-service
        - zipkin
