eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: eureka-server
server:
  port: 8888
spring:
  application:
    name: PAYMENT-SERVICE
    
    
    
    
