eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    hostname: eureka-server
server:
  port: 8888
spring:
  application:
    name: PAYMENT-SERVICE
    
    
    
    
