eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    hostname: eureka-server
server:
  port: 8888
spring:
  application:
    name: PAYMENT-SERVICE

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
    
    
    
    
