eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: eureka-server
server:
  port: 9999
spring:
  application:
    name: AMAZON-SHOPPING
