spring:
  cloud:
    config:
      enabled: true
      uri:
      - http://config-server:8882
      fail-fast: true
      retry:
        max-attempts: 20
  application:
    name: getemployee-client
    
server:
  port: 8884
