spring:
  config:
    import:
    - optional:configserver:http://config-server:8882
   
  cloud:
    config:
      enabled: true
      fail-fast: true
      retry:
        max-attempts: 20
    
server:
  port: 8884
