server:
  port: 8882
spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/sekharbabug/config-server
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"      
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: eureka-server                       