server:
  port: 8882
spring:
  application:
    name: CONFIG-SERVER
    

 cloud:
    config:
      server:
        git:
          uri: https://github.com/sekharbabug/config-server
          clone-on-start: true
          
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"                     
